FROM %DOCKER_REGISTRY%docker-library-alpine

MAINTAINER Serge Fomin <serge.fo@gmail.com>

EXPOSE 80 443

RUN apk update \
  && apk add \
    ca-certificates \
    nginx \
  && rm -rf /tmp/* /var/cache/apk/*

RUN mkdir /app

COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf

CMD nginx -g daemon off;
